### ISSUE TITLE
Multiple specs

### ISSUE THREAD

**Issue by RomanHotsiy** [Redocly/create-openapi-repo#1]
It would be useful to have a possibility to host more than one specs which can share definitions.

Ideas:
- a main page of the repo should contain some general API/APIs description and links to each of spec/subspecs
- sticky header with crosslinks

What problems it solves:
- allows to easily split big specs into smaller
- reduces duplication by using shared definitions

Some implementation details:
- definitions are shared
- each spec has its own entry point
- paths of the concrete spec/subspec should be stored in the folder named the same as spec entry point

**Comment by HazemKhaled** [comment]
There an example here
https://github.com/Redocly/redoc/blob/gh-pages/examples/multiple-apis/index.html

**Comment by RomanHotsiy** [comment]
Implemented with new openapi-cli
