### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by wshayes** [Redocly/create-openapi-repo#11]
Anyone else getting this error?

I'm using: 
  node -v:  v7.7.3
  npm -v: 4.2.0

and getting the following error:

    yo openapi-repo

     _-----_
    |       |    ╭──────────────────────────╮
    |--(o)--|    │      Welcome to the      │
   `---------´   │  OpenAPI-Repo generator! │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

    ? Do you already have OpenAPI/Swagger spec for your API? (y/N)

    events.js:163
          throw er; // Unhandled 'error' event
          ^

    TypeError: this.env.adapter.prompt(...).then is not a function
        at child.Base.prompt (/opt/local/lib/node_modules/generator-openapi-
    repo/node_modules/yeoman-generator/lib/base.js:240:45)

**Comment by RomanHotsiy** [comment]
Stale.
