### ISSUE TITLE
error installing generator

### ISSUE THREAD

**Issue by work3t** [Redocly/create-openapi-repo#17]
Please help!

sudo  npm install -g generator-openapi-repo

> jsonpath@0.2.12 postinstall /usr/local/lib/node_modules/generator-openapi-repo/node_modules/jsonpath
> node lib/aesprim.js > generated/aesprim-browser.js

sh: generated/aesprim-browser.js: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jsonpath@0.2.12 postinstall: `node lib/aesprim.js > generated/aesprim-browser.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jsonpath@0.2.12 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/server/.npm/_logs/2018-01-11T08_47_17_808Z-debug.log

**Comment by RomanHotsiy** [comment]
Closing as stale, shouldn't be an issue anymore
