### ISSUE TITLE
support separate files for tag descriptions

### ISSUE THREAD

**Issue by ShangyanLi** [Redocly/create-openapi-repo#28]
I've really enjoyed using the tool for my project documentation. 

In addition to API specs, however, I'm also hosting a lot of general software design documentation (that doesn't involve REST API paths at all, like class overview, state diagrams, execution concept & flow, etc.) using Markdown. Right now I'm using tags + x-tagGroups, where the `description` field for some tags can be hundreds and thousands of lines of Markdown, and it's all crammed inside `spec/swagger.yaml`. 

It would be extremely helpful to support storing tag descriptions in separate files in another sub-directory. Otherwise the swagger.yaml file would have 10k+ lines and collaborative documentation becomes virtually unfeasible. 

IMO adding this option would greatly extend the tool and make it an ideal option for not just API spec but overall software documentation as well. Any thoughts? And thanks for the great work!

**Comment by RomanHotsiy** [comment]
It is partly supported now using $refs for description https://redoc.ly/docs/api-reference-docs/embedded-markdown/
