### ISSUE TITLE
Swagger UI isn't there

### ISSUE THREAD

**Issue by neumantm** [Redocly/create-openapi-repo#40]
When generating my api repo I answered yes to whether swagger ui should be installed.
But when running npm start `localhost:8080/swagger-ui/` returns a `404`. Same when deploying to gh-pages.

**Comment by philals** [comment]
Just created a test as well.

Looks like swagger-ui has been removed in favor of ReDoc. Looks good.

I think the README template is still referencing SwaggerUI
