### ISSUE TITLE
display code samples when path has a parameter in it

### ISSUE THREAD

**Issue by coderbec** [Redocly/create-openapi-repo#44]
I have a created a folder that is "v1@messages" which has a post.cs file in it for the csharp code sample, but when I put the get.cs file in there and try to build it produces the following error: 

throw Error('Code sample for non-existing operation: "' + path + '",' + verb);

If I move it out of there into it's own folder it produces the same error. I have tried with this folder name: 

"v1@messages@{messageId}"
and 
"v1@messages@messageId"

What else should I try? Also, this should be updated in the readme for code samples.

**Comment by adamaltman** [comment]
Sorry, I didn't see this before.  

We are releasing a new version soon where this will be moot.  

However, what is the filename for the corresponding path?

**Comment by bel0v** [comment]
I'm getting the same error. I've created a new repo and following the cli steps added an existing spec.yaml and enabled the "splitting" setting. It split the file for me allright, with `paths` and `components`  folders, but it cannot build or run due to this error ^

**Comment by RomanHotsiy** [comment]
Closing as stale. Feel free to reopen if this is still an issue.
