### ISSUE TITLE
code samples no longer being generated with v3.0.1

### ISSUE THREAD

**Issue by tony-assembly** [Redocly/create-openapi-repo#49]
Tried generating a new spec using `create-openapi-repo .` and even though there are code samples generated they do not appear in the rendered document

**Comment by RomanHotsiy** [comment]
Thanks for reporting. We'll fix that...

You have to link code-samples directly using `$ref`, see example here: https://github.com/Rebilly/RebillyAPI/blob/master/openapi/paths/authentication-tokens.yaml#L38-L41

**Comment by tony-assembly** [comment]
> Thanks for reporting. We'll fix that...
> 
> You have to link code-samples directly using `$ref`, see example here: https://github.com/Rebilly/RebillyAPI/blob/master/openapi/paths/authentication-tokens.yaml#L38-L41

Ok awesome. Will give that a go!

**Comment by RomanHotsiy** [comment]
Should be fixed in 3.0.2
