### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled promise rejection 

### ISSUE THREAD

**Issue by ZouZou** [Redocly/create-openapi-repo#55]
I am just starting with this repo, I did everything according to the docs however when I finish the last step and get the following:

> Success! Created openapi folder.
You can run several commands:

  npm start
    Starts the development server.

  npm run build
    Bundles the definition.

  npm test
    Validates the definition.

We suggest that you begin by typing:

  npm start

> 

I try to use npm start and i get the below:

> 
(node:29112) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): YAMLException: unknown escape sequence at line 3, column 18:
      main: "openapi\openapi.yaml"
                     ^
(node:29112) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

> 

Can you help please?

**Comment by RomanHotsiy** [comment]
Dup of https://github.com/Redocly/openapi-cli/issues/110
