### ISSUE TITLE
Option to split files only where OpenAPI expect references?

### ISSUE THREAD

**Issue by mimkorn** [Redocly/create-openapi-repo#72]
Hi, 

lovely tool, thanks! We were thinking of using it in our company, but we were also considering using Stoplight Studio. However, no tools out there at the moment expect some of the splitting your tool does. Here I mean referring to markdown description files via $ref and those special filenames for paths.

Would it be possible with some flag to do the initial OpenAPI spec split only into files that the OpenAPI spec officially supports, so the repo could then be consumed by some of these editors? 

Thanks.

**Comment by adamaltman** [comment]
This is done (in a separate Redocly CLI `split` command): https://redocly.com/docs/cli/commands/split/
