### ISSUE TITLE
Error message shows up: 'Every API should have security defined on the root level or for each operation'

### ISSUE THREAD

**Issue by AviandraPutri-Jubelio** [Redocly/create-openapi-repo#85]
I used to split my openapi files using this 'create-openapi-method', it was usually ok, but today, September 19th, this error notification shows up and i don't understand why. Could you please explain this error to me?

![image](https://user-images.githubusercontent.com/111033787/190943172-2dcd5659-913d-4c28-b552-e7be37e12d24.png)

**Comment by RomanHotsiy** [comment]
I answered you in the other issue you opened: https://github.com/Redocly/redocly-cli/issues/877
